name: Build And Test

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

env:
  BUILD_DIRECTORY: Build
  RUNTIME_DIRECTORY: Build/Bin

jobs:
  build_and_test:
    strategy:
      matrix:
        build_type: [Release, Debug]
        # TODO: Add windows-latest
        # TODO: Add compilers matrix
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
      if: matrix.platform != 'windows-latest'
    
    - name: Setup Boost using Homebrew
      shell: bash
      run: brew install boost
      if: matrix.platform != 'windows-latest'
          
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/${{env.BUILD_DIRECTORY}}

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}
      env:
        BUILD_TYPE: ${{matrix.build_type}}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/${{env.RUNTIME_DIRECTORY}}
      run: ./MemoryTest

    - name: Run benchmark
      working-directory: ${{github.workspace}}/${{env.RUNTIME_DIRECTORY}}
      run: ./MemoryPoolBenchmark
