name: Build And Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_DIRECTORY: Build
  RUNTIME_DIRECTORY: Build/Bin

jobs:
  build_and_test:
    strategy:
      matrix:
        build_type: [ Release, Debug ]
        # TODO: Add compilers matrix
        platform: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    defaults:
      run:
        shell: bash

    runs-on: ${{matrix.platform}}

    env:
      EXECUTABLE_SUFFIX: ${{matrix.platform == 'windows-latest' && '.exe' || ''}}

    steps:
      - name: Setup Boost environment
        run: echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
        if: matrix.platform == 'windows-latest' || matrix.platform == 'ubuntu-latest'

      - name: Setup Boost using Homebrew
        run: brew install boost
        if: matrix.platform == 'macos-latest'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup build environment
        run: cmake -E make_directory ${{github.workspace}}/${{env.BUILD_DIRECTORY}}

      - name: Configure CMake
        working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}
        env:
          BUILD_TYPE: ${{matrix.build_type}}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/${{env.BUILD_DIRECTORY}}
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/${{env.RUNTIME_DIRECTORY}}
        run: ./MemoryTest$EXECUTABLE_SUFFIX

      - name: Run benchmarks
        working-directory: ${{github.workspace}}/${{env.RUNTIME_DIRECTORY}}
        run: ./MemoryPoolBenchmark$EXECUTABLE_SUFFIX
